"""initial schema

Revision ID: b6d5e152d4d9
Revises:
Create Date: 2026-08-18 16:16:33.898489+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b6d5e152d4d9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Колонка vector и индекс hnsw существуют только при включённом расширении.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding_model", sa.String(length=120), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("similarity_threshold", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("max_chunks", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("max_chunks > 0", name=op.f("ck_knowledge_bases_max_chunks_positive")),
        sa.CheckConstraint(
            "similarity_threshold >= 0 AND similarity_threshold <= 1",
            name=op.f("ck_knowledge_bases_similarity_threshold_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
        sa.UniqueConstraint("name", name=op.f("uq_knowledge_bases_name")),
    )
    op.create_table(
        "proxies",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scheme", sa.String(length=16), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password_ct", sa.LargeBinary(), nullable=True),
        sa.Column("password_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("password_key_id", sa.String(length=32), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scheme IN ('socks5', 'socks4', 'http', 'mtproxy')",
            name=op.f("ck_proxies_scheme_supported"),
        ),
        sa.CheckConstraint("port > 0 AND port <= 65535", name=op.f("ck_proxies_port_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxies")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "OPERATOR", "VIEWER", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_table(
        "workers",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("STARTING", "HEALTHY", "DEGRADED", "ERROR", "STOPPED", name="worker_status"),
            nullable=False,
        ),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accounts_count", sa.Integer(), nullable=False),
        sa.Column("queue_size", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workers")),
    )
    op.create_index(
        "ix_workers_heartbeat_at", "workers", [sa.literal_column("heartbeat_at DESC")], unique=False
    )
    op.create_index("ix_workers_status", "workers", ["status"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "AUTHENTICATING",
                "ONLINE",
                "OFFLINE",
                "ERROR",
                "DISABLED",
                "AUTH_REQUIRED",
                name="account_status",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("proxy_id", sa.UUID(), nullable=True),
        sa.Column("worker_id", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_accounts_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proxy_id"],
            ["proxies.id"],
            name=op.f("fk_accounts_proxy_id_proxies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
            name=op.f("fk_accounts_worker_id_workers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index("ix_accounts_owner_user_id", "accounts", ["owner_user_id"], unique=False)
    op.create_index("ix_accounts_status", "accounts", ["status"], unique=False)
    op.create_index("ix_accounts_worker_id", "accounts", ["worker_id"], unique=False)
    op.create_index(
        "uq_accounts_tg_user_id",
        "accounts",
        ["tg_user_id"],
        unique=True,
        postgresql_where=sa.text("tg_user_id IS NOT NULL"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_actor_user_id", "audit_logs", ["actor_user_id"], unique=False)
    op.create_index(
        "ix_audit_logs_created_at",
        "audit_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PARSING",
                "EMBEDDING",
                "READY",
                "FAILED",
                name="knowledge_document_status",
            ),
            nullable=False,
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_knowledge_documents_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
        sa.UniqueConstraint(
            "knowledge_base_id", "sha256", name="uq_knowledge_documents_knowledge_base_id_sha256"
        ),
    )
    op.create_index(
        "ix_knowledge_documents_status", "knowledge_documents", ["status"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "HUMAN_HANDOFF",
                "ACCOUNT_ERROR",
                "NEW_LEAD",
                "WORKER_DOWN",
                "AI_BUDGET",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_table(
        "scenarios",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("temperature", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("tone", sa.String(length=64), nullable=True),
        sa.Column("max_reply_length", sa.Integer(), nullable=True),
        sa.Column("context_messages", sa.Integer(), nullable=True),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=True),
        sa.Column("require_knowledge_grounding", sa.Boolean(), nullable=False),
        sa.Column("fallback_text", sa.Text(), nullable=True),
        sa.Column("human_handoff_enabled", sa.Boolean(), nullable=False),
        sa.Column("min_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "context_messages IS NULL OR context_messages > 0",
            name=op.f("ck_scenarios_context_messages_positive"),
        ),
        sa.CheckConstraint(
            "min_confidence IS NULL OR (min_confidence >= 0 AND min_confidence <= 1)",
            name=op.f("ck_scenarios_min_confidence_range"),
        ),
        sa.CheckConstraint(
            "temperature IS NULL OR (temperature >= 0 AND temperature <= 2)",
            name=op.f("ck_scenarios_temperature_range"),
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_scenarios_knowledge_base_id_knowledge_bases"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
        sa.UniqueConstraint("name", name=op.f("uq_scenarios_name")),
    )
    op.create_index("ix_scenarios_enabled", "scenarios", ["enabled"], unique=False)
    op.create_table(
        "chats",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PRIVATE", "GROUP", "SUPERGROUP", "CHANNEL", name="chat_type"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("members_count", sa.Integer(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_chats_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
        sa.UniqueConstraint("account_id", "tg_chat_id", name="uq_chats_account_id_tg_chat_id"),
    )
    op.create_index(
        "ix_chats_monitored",
        "chats",
        ["account_id"],
        unique=False,
        postgresql_where=sa.text("monitored IS TRUE"),
    )
    op.create_index("ix_chats_tg_chat_id", "chats", ["tg_chat_id"], unique=False)
    op.create_table(
        "knowledge_chunks",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_chunks_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_knowledge_chunks_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint("document_id", "ord", name="uq_knowledge_chunks_document_id_ord"),
    )
    op.create_index(
        "ix_knowledge_chunks_embedding",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_knowledge_chunks_knowledge_base_id",
        "knowledge_chunks",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_table(
        "processed_messages",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "claimed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_processed_messages_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "account_id", "tg_chat_id", "tg_message_id", name=op.f("pk_processed_messages")
        ),
    )
    op.create_index(
        "ix_processed_messages_claimed_at", "processed_messages", ["claimed_at"], unique=False
    )
    op.create_table(
        "rules",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("stop_on_match", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.Enum("CHAT_MONITOR", "DIALOG", name="rule_scope"), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("regex", sa.Text(), nullable=True),
        sa.Column("ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("ai_threshold", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "cooldown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "REPLY",
                "NOTIFY_ADMIN",
                "SAVE_LEAD",
                "TAG_USER",
                "ESCALATE_TO_HUMAN",
                "IGNORE",
                name="action_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "action_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT ai_enabled OR ai_threshold IS NOT NULL",
            name=op.f("ck_rules_ai_threshold_required"),
        ),
        sa.CheckConstraint(
            "ai_threshold IS NULL OR (ai_threshold >= 0 AND ai_threshold <= 1)",
            name=op.f("ck_rules_ai_threshold_range"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_rules_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    op.create_index(
        "ix_rules_enabled_priority",
        "rules",
        ["enabled", sa.literal_column("priority DESC")],
        unique=False,
    )
    op.create_index("ix_rules_scope", "rules", ["scope"], unique=False)
    op.create_table(
        "telegram_sessions",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("STRING", "FILE", name="session_kind"), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("alg", sa.String(length=32), nullable=False),
        sa.Column("api_id_ct", sa.LargeBinary(), nullable=True),
        sa.Column("api_id_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("api_hash_ct", sa.LargeBinary(), nullable=True),
        sa.Column("api_hash_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_telegram_sessions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_sessions")),
        sa.UniqueConstraint("account_id", name=op.f("uq_telegram_sessions_account_id")),
    )
    op.create_table(
        "conversations",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("peer_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ACTIVE",
                "QUALIFIED",
                "HOT",
                "HUMAN_REQUIRED",
                "CLOSED",
                name="conversation_status",
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_upto_message_id", sa.BigInteger(), nullable=True),
        sa.Column("summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("ai_replies_in_row", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_conversations_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_conversations_chat_id_chats"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_conversations_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "account_id", "peer_tg_id", name="uq_conversations_account_id_peer_tg_id"
        ),
    )
    op.create_index(
        "ix_conversations_last_message_at",
        "conversations",
        [sa.literal_column("last_message_at DESC")],
        unique=False,
    )
    op.create_index("ix_conversations_status", "conversations", ["status"], unique=False)
    op.create_table(
        "rule_accounts",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_rule_accounts_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
            name=op.f("fk_rule_accounts_rule_id_rules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("rule_id", "account_id", name=op.f("pk_rule_accounts")),
    )
    op.create_index("ix_rule_accounts_account_id", "rule_accounts", ["account_id"], unique=False)
    op.create_table(
        "rule_chats",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_rule_chats_chat_id_chats"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["rules.id"], name=op.f("fk_rule_chats_rule_id_rules"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("rule_id", "chat_id", name=op.f("pk_rule_chats")),
    )
    op.create_index("ix_rule_chats_chat_id", "rule_chats", ["chat_id"], unique=False)
    op.create_table(
        "leads",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("source_chat_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column("intent", sa.String(length=64), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "COLD", "WARM", "HOT", "CONVERTED", "LOST", name="lead_status"),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score >= 0 AND score <= 100", name=op.f("ck_leads_score_range")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_leads_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_leads_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_leads_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_chat_id"],
            ["chats.id"],
            name=op.f("fk_leads_source_chat_id_chats"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("account_id", "tg_user_id", name="uq_leads_account_id_tg_user_id"),
    )
    op.create_index(
        "ix_leads_created_at", "leads", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(
        "ix_leads_status_score", "leads", ["status", sa.literal_column("score DESC")], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=False),
        sa.Column("sender_tg_id", sa.BigInteger(), nullable=True),
        sa.Column("sender_username", sa.String(length=64), nullable=True),
        sa.Column("sender_display_name", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reply_to_tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("is_incoming", sa.Boolean(), nullable=False),
        sa.Column("is_outgoing", sa.Boolean(), nullable=False),
        sa.Column("is_forwarded", sa.Boolean(), nullable=False),
        sa.Column("is_bot_reply", sa.Boolean(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "PHOTO",
                "VIDEO",
                "DOCUMENT",
                "AUDIO",
                "VOICE",
                "STICKER",
                "ANIMATION",
                "POLL",
                "LOCATION",
                "CONTACT",
                "WEBPAGE",
                "OTHER",
                name="media_type",
            ),
            nullable=True,
        ),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column(
            "processed_status",
            sa.Enum("PENDING", "SKIPPED", "MATCHED", "REPLIED", "FAILED", name="processed_status"),
            nullable=False,
        ),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "is_incoming <> is_outgoing", name=op.f("ck_messages_direction_exclusive")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_messages_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_messages_chat_id_chats"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["rules.id"], name=op.f("fk_messages_rule_id_rules"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "account_id",
            "tg_chat_id",
            "tg_message_id",
            name="uq_messages_account_id_tg_chat_id_tg_message_id",
        ),
    )
    op.create_index(
        "ix_messages_account_id_date",
        "messages",
        ["account_id", sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_messages_chat_id_date",
        "messages",
        ["chat_id", sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_messages_conversation_id_date", "messages", ["conversation_id", "date"], unique=False
    )
    op.create_index("ix_messages_created_at", "messages", ["created_at"], unique=False)
    op.create_index("ix_messages_processed_status", "messages", ["processed_status"], unique=False)
    op.create_index("ix_messages_sender_tg_id", "messages", ["sender_tg_id"], unique=False)
    op.create_table(
        "actions",
        sa.Column(
            "type",
            sa.Enum(
                "REPLY",
                "NOTIFY_ADMIN",
                "SAVE_LEAD",
                "TAG_USER",
                "ESCALATE_TO_HUMAN",
                "IGNORE",
                name="action_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VALIDATING",
                "READY",
                "SENDING",
                "SENT",
                "FAILED",
                "CANCELLED",
                "REJECTED",
                name="action_status",
            ),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("reply_text", sa.Text(), nullable=True),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_actions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_actions_chat_id_chats"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_actions_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_actions_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["rules.id"], name=op.f("fk_actions_rule_id_rules"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_actions_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_actions_dedup_key")),
    )
    op.create_index(
        "ix_actions_account_id_created_at",
        "actions",
        ["account_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_actions_conversation_id", "actions", ["conversation_id"], unique=False)
    op.create_index(
        "ix_actions_status_scheduled_at", "actions", ["status", "scheduled_at"], unique=False
    )
    op.create_table(
        "ai_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("ANALYZE", "GENERATE", "SUMMARIZE", "EMBED", name="ai_purpose"),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_ai_requests_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_ai_requests_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_ai_requests_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_requests")),
    )
    op.create_index(
        "ix_ai_requests_created_at",
        "ai_requests",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_ai_requests_purpose_created_at",
        "ai_requests",
        ["purpose", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_memory",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("peer_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_user_memory_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_user_memory_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
            name=op.f("fk_user_memory_source_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_memory")),
        sa.UniqueConstraint(
            "account_id", "peer_tg_id", "key", name="uq_user_memory_account_id_peer_tg_id_key"
        ),
    )
    op.create_table(
        "action_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
            name=op.f("fk_action_logs_action_id_actions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_logs")),
    )
    op.create_index("ix_action_logs_action_id_at", "action_logs", ["action_id", "at"], unique=False)
    op.create_table(
        "event_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "MESSAGE_RECEIVED",
                "MESSAGE_SKIPPED",
                "RULE_MATCH",
                "AI_ANALYSIS",
                "AI_GENERATION",
                "VALIDATION_FAILED",
                "COOLDOWN_BLOCKED",
                "ACTION_CREATED",
                "ACTION_SENT",
                "ACTION_FAILED",
                "ACCOUNT_CONNECTED",
                "ACCOUNT_DISCONNECTED",
                "ACCOUNT_AUTH_REQUIRED",
                "LEAD_UPDATED",
                "HUMAN_HANDOFF",
                "ERROR",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("action_id", sa.UUID(), nullable=True),
        sa.Column("worker_id", sa.UUID(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_event_logs_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
            name=op.f("fk_event_logs_action_id_actions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_event_logs_chat_id_chats"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_event_logs_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["rules.id"], name=op.f("fk_event_logs_rule_id_rules"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_event_logs_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
            name=op.f("fk_event_logs_worker_id_workers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_logs")),
    )
    op.create_index(
        "ix_event_logs_account_id_ts",
        "event_logs",
        ["account_id", sa.literal_column("ts DESC")],
        unique=False,
    )
    op.create_index(
        "ix_event_logs_event_type_ts",
        "event_logs",
        ["event_type", sa.literal_column("ts DESC")],
        unique=False,
    )
    op.create_index("ix_event_logs_message_id", "event_logs", ["message_id"], unique=False)
    op.create_index("ix_event_logs_ts", "event_logs", [sa.literal_column("ts DESC")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_logs_ts", table_name="event_logs")
    op.drop_index("ix_event_logs_message_id", table_name="event_logs")
    op.drop_index("ix_event_logs_event_type_ts", table_name="event_logs")
    op.drop_index("ix_event_logs_account_id_ts", table_name="event_logs")
    op.drop_table("event_logs")
    op.drop_index("ix_action_logs_action_id_at", table_name="action_logs")
    op.drop_table("action_logs")
    op.drop_table("user_memory")
    op.drop_index("ix_ai_requests_purpose_created_at", table_name="ai_requests")
    op.drop_index("ix_ai_requests_created_at", table_name="ai_requests")
    op.drop_table("ai_requests")
    op.drop_index("ix_actions_status_scheduled_at", table_name="actions")
    op.drop_index("ix_actions_conversation_id", table_name="actions")
    op.drop_index("ix_actions_account_id_created_at", table_name="actions")
    op.drop_table("actions")
    op.drop_index("ix_messages_sender_tg_id", table_name="messages")
    op.drop_index("ix_messages_processed_status", table_name="messages")
    op.drop_index("ix_messages_created_at", table_name="messages")
    op.drop_index("ix_messages_conversation_id_date", table_name="messages")
    op.drop_index("ix_messages_chat_id_date", table_name="messages")
    op.drop_index("ix_messages_account_id_date", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_leads_status_score", table_name="leads")
    op.drop_index("ix_leads_created_at", table_name="leads")
    op.drop_table("leads")
    op.drop_index("ix_rule_chats_chat_id", table_name="rule_chats")
    op.drop_table("rule_chats")
    op.drop_index("ix_rule_accounts_account_id", table_name="rule_accounts")
    op.drop_table("rule_accounts")
    op.drop_index("ix_conversations_status", table_name="conversations")
    op.drop_index("ix_conversations_last_message_at", table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("telegram_sessions")
    op.drop_index("ix_rules_scope", table_name="rules")
    op.drop_index("ix_rules_enabled_priority", table_name="rules")
    op.drop_table("rules")
    op.drop_index("ix_processed_messages_claimed_at", table_name="processed_messages")
    op.drop_table("processed_messages")
    op.drop_index("ix_knowledge_chunks_knowledge_base_id", table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_embedding",
        table_name="knowledge_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_chats_tg_chat_id", table_name="chats")
    op.drop_index(
        "ix_chats_monitored", table_name="chats", postgresql_where=sa.text("monitored IS TRUE")
    )
    op.drop_table("chats")
    op.drop_index("ix_scenarios_enabled", table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notifications")
    op.drop_index("ix_knowledge_documents_status", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        "uq_accounts_tg_user_id",
        table_name="accounts",
        postgresql_where=sa.text("tg_user_id IS NOT NULL"),
    )
    op.drop_index("ix_accounts_worker_id", table_name="accounts")
    op.drop_index("ix_accounts_status", table_name="accounts")
    op.drop_index("ix_accounts_owner_user_id", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index("ix_workers_status", table_name="workers")
    op.drop_index("ix_workers_heartbeat_at", table_name="workers")
    op.drop_table("workers")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_table("users")
    op.drop_table("proxies")
    op.drop_table("knowledge_bases")
    # ### end Alembic commands ###

    # Нативные enum-типы переживают drop_table и мешают повторному upgrade.
    op.execute("DROP TYPE IF EXISTS account_status")
    op.execute("DROP TYPE IF EXISTS action_status")
    op.execute("DROP TYPE IF EXISTS action_type")
    op.execute("DROP TYPE IF EXISTS ai_purpose")
    op.execute("DROP TYPE IF EXISTS chat_type")
    op.execute("DROP TYPE IF EXISTS conversation_status")
    op.execute("DROP TYPE IF EXISTS event_type")
    op.execute("DROP TYPE IF EXISTS knowledge_document_status")
    op.execute("DROP TYPE IF EXISTS lead_status")
    op.execute("DROP TYPE IF EXISTS media_type")
    op.execute("DROP TYPE IF EXISTS notification_type")
    op.execute("DROP TYPE IF EXISTS processed_status")
    op.execute("DROP TYPE IF EXISTS rule_scope")
    op.execute("DROP TYPE IF EXISTS session_kind")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS worker_status")
    op.execute("DROP EXTENSION IF EXISTS vector")
