"""chat avatar columns

Revision ID: bbfbc9b62d8c
Revises: b6d5e152d4d9
Create Date: 2026-08-19 11:09:41.692380+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "bbfbc9b62d8c"
down_revision: str | None = "b6d5e152d4d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("avatar", sa.LargeBinary(), nullable=True))
    op.add_column("chats", sa.Column("avatar_mime", sa.String(length=32), nullable=True))
    op.add_column(
        "chats", sa.Column("avatar_fetched_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "avatar_fetched_at")
    op.drop_column("chats", "avatar_mime")
    op.drop_column("chats", "avatar")
    # ### end Alembic commands ###
